import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'lat_lng.dart';
import 'place.dart';
import '../backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../auth/auth_util.dart';

int? getLength(List<ContactsRecord>? myList) {
  int? length = myList?.length;
  return length;
}

String? getDomain(String emailAddress) {
  int atLocation = emailAddress.indexOf('@') + 1;
  String finalResult = emailAddress.substring(atLocation);
  return finalResult;
}

String? getDocumentId(DocumentReference profileReference) {
  return profileReference.id;
}

String? getPublicProfileUrl(DocumentReference profileReference) {
  return "https://beenie.nexl.cloud/publicProfile/" + profileReference.id;
}

DocumentReference getProfileFromURL(String profileURL) {
  String profileId =
      profileURL.substring(profileURL.indexOf('publicProfile/') + 14);

  return FirebaseFirestore.instance.doc('profiles/' + profileId);
}

DocumentReference? getBeenieCardProfile(String cardID) {
  return FirebaseFirestore.instance.doc('beeniecards/' + cardID);
}

dynamic buildVeroProfileData(ProfilesRecord profileDoc) {
  String jsonData = "{\"first_name\": \"" +
      profileDoc.firstName! +
      "\", \"last_name\": \"" +
      profileDoc.lastName! +
      "\", \"job_title\": \"" +
      profileDoc.jobTitle! +
      "\", \"work_email\": \"" +
      profileDoc.emailAddress! +
      "\"}";
  return jsonData;
}

List<String> getCountryList() {
  const countryList = [
    "Afghanistan",
    "Åland Islands",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas (the)",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia (Plurinational State of)",
    "Bonaire, Sint Eustatius and Saba",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory (the)",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands (the)",
    "Central African Republic (the)",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands (the)",
    "Colombia",
    "Comoros (the)",
    "Congo (the Democratic Republic of the)",
    "Congo (the)",
    "Cook Islands (the)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czechia",
    "Côte d'Ivoire",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic (the)",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands (the) [Malvinas]",
    "Faroe Islands (the)",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories (the)",
    "Gabon",
    "Gambia (the)",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Holy See (the)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran (Islamic Republic of)",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea (the Democratic People's Republic of)",
    "Korea (the Republic of)",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic (the)",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands (the)",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia (Federated States of)",
    "Moldova (the Republic of)",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands (the)",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger (the)",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands (the)",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine, State of",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines (the)",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Republic of North Macedonia",
    "Romania",
    "Russian Federation (the)",
    "Rwanda",
    "Réunion",
    "Saint Barthélemy",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin (French part)",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten (Dutch part)",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan (the)",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan (Province of China)",
    "Tajikistan",
    "Tanzania, United Republic of",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands (the)",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates (the)",
    "United Kingdom of Great Britain and Northern Ireland (the)",
    "United States Minor Outlying Islands (the)",
    "United States of America (the)",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela (Bolivarian Republic of)",
    "Viet Nam",
    "Virgin Islands (British)",
    "Virgin Islands (U.S.)",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ];

  return countryList;
}

List<String>? getJobTitleList() {
  const jobList = [
    "Marketing Manager",
    "Head Of Brand Marketing",
    "Head Of Marketing",
    "Head of IT & Digital Transformation",
    "Marketing Director",
    "VP Global Marketing",
    "Managing Partner",
    "VP, Marketing",
    "Business Development Director",
    "Managing Director ",
    "Managing Director",
    "GC and CCO",
    "CEO",
    "Director of Demand Generation",
    "Global Marketing Manager",
    "Senior Digital Marketing Manager",
    "Head of Advertising & Sponsorship",
    "Commercial Director",
    "Marketing and Brand Manager",
    "Chief Executive Officer",
    "CEO & Co-Founder",
    "General Counsel",
    "Director of Marketing",
    "Participant @ Techstars London 2021",
    "Corporate Counsel",
    "Chief Marketing Officer",
    "Chief Finance Officer",
    "Founder Director",
    "Director Practice Development",
    "Board Advisor",
    "Managing Director, Europe",
    "Head of Practice Transformation",
    "Associate Lawyer",
    "CEO and Founder",
    "President and CEO",
    "Director, Marketing",
    "Founder and CEO",
    "Advisor & Co-founder",
    "Head of Digital Services  ",
    "Deputy Chief Executive Officer",
    "University Lecturer",
    "Chief Executive",
    "Managing Director, Australia",
    "Managing Partner ",
    "Executive Director",
    "Founder and Owner",
    "Executive Partner",
    "Head Of Digital",
    "Managing Partner & Co-founder",
    "Owner and Executive Chair",
    "Partner",
    "Managing Partner, Dubai",
    "Director & Founder",
    "Director - Business Development",
    "Chief Commercial Officer",
    "Senior Business Development Manager",
    "Director Of Business Development",
    "Vice President Marketing",
    "Chief Revenue Officer",
    "Member Board Of Trustees",
    "M&A Partner",
    "Chief Operating Officer",
    "Managing Partner, WC",
    "Co-Founder",
    "Group Chief Legal Officer",
    "Head of Patent Analytics",
    "CEO ANZ",
    "Strategy and Operations Manager",
    "President",
    "Head of Digital & Data",
    "Patent Bar Review Lecturer",
    "Associate Director",
    "Expert",
    "Legal Specialist",
    "Trustee Director",
    "Managing Director - Paris",
    "Co-Founder and CEO",
    "Adjunct Professor",
    "Fellow",
    "Owner",
    "Expert Legal Consultant",
    "Brand Ambassador",
    "Founder & CEO",
    "Senior Managing Director",
    "Attorney, CPA, Managing Partner",
    "Chair",
    "CEO & Founding Partner",
    "President, Shareholder",
    "Co-Chair, Emerging Leaders Council",
    "Digital Marketing Manager",
    "Board Member",
    "Global Marketing Director",
    "Brand & Marketing Manager",
    "Head of Marketing & Communications ",
    "Head of Communication & Marketing",
    "Senior Director of Marketing",
    "Strategy Director",
    "S√≥cio Presidente",
    "Director - Legal & Compliance",
    "Head of Strategy and Operations",
    "San Jose Chapter Co-Chair",
    "Partner (M&A / Hi-Tech)",
    "Consultant",
    "Principal",
    "Director, Markets & Growth EMEA",
    "Mentor",
    "Founder and Principal Attorney",
    "Co - Chief Operating Officer",
    "President / Lawyer",
    "Member",
    "Founder and Managing Partner",
    "Adjunct Faculty",
    "VP of the Board and Legal Counsel ",
    "Director of Market Development",
    "Founding Partner and CEO",
    "Guardian Ad Litem",
    "Member Board Of Directors",
    "Group CEO and Co-Founder",
    "Entrepreneur in Residence",
    "International Arbitrator/Mediator",
    "Senior Brand Manager",
    "Senior Marketing Manager",
    "Founder and Director",
    "Director of Strategic Accounts",
    "Classroom Assistant",
    "Marketing Operations Director",
    "Global Chief Marketing Officer",
    "Director, Corporate Counsel",
    "Head Of Business Development",
    "Chief Transformation Officer",
    "Head of Legal Practice Development",
    "Founding Member",
    "Founding Partner / ICT-jurist",
    "Legal Associate",
    "Enterprise Development",
    "Founder & Managing Partner",
    "NV State Managing Attorney",
    "Founder",
    "Chairman",
    "Chief Strategy Officer (CSO)",
    "Director & CEO",
    "Co Founder",
    "Managing Partner, Hong Kong",
    "Managing Partner / Owner",
    "Co-Founder - Tax Attorney",
    "Executive Co-Chairman/Founder",
    "Avocat und Rechtsanwalt (Partner)",
    "Chairman of the Board",
    "Board Chair Emeritus",
    "Founder and Creator",
    "Business Account Manager",
    "Executive Chairman",
    "Senior Marketing Director",
    "Head Of Global Sales",
    "VP, Business Development, Legal",
    "Senior Director",
    "Senior Client Marketing Manager",
    "Digital & Design Marketing Manager",
    "Sales Executive",
    "Head of Transformation and Projects",
    "Head of Marketing & PR",
    "Managing Director of Litigation",
    "Co CEO",
    "Executive Committee Member",
    "CEO , Abogado, Cofundador",
    "Senior Partner and Head of M&A",
    "Director, Co-Founder ",
    "Adjunct Professor Of Law",
    "Co-Managing Partner",
    "International Managing Partner",
    "International Attorney",
    "Chief Sales & Marketing Officer",
    "President, North America",
    "Director Of Client Relations",
    "Non Executive Director (ASX)",
    "Owner and Partner",
    "Group CEO",
    "Director, Foundation Board",
    "CEO/Director of Clerking",
    "Associate",
    "Strategic Managing Partner",
    "Founder Partner",
    "Trustee",
    "Member - Alumni Executive Committee",
    "Regular Contributor",
    "Attorney",
    "President and General Counsel",
    "Corporate and Commercial Associate",
    "Director of Digital Experience",
    "Chief Member",
    "Head Of Marketing Communications",
    "Head of Marketing ",
    "Legal Engagement Manager",
    "Director, IT Services & Operations",
    "Chief Executive Officer ",
    "Marketing Manager, Konexo UK",
    "Attorney, Head of acquisitions",
    "Director of Marketing ",
    "President & Chief Executive Officer",
    "Head of Restructuring",
    "Vice President of Strategy",
    "MS Dynamics 365 CRM Consultant",
    "Chief People, co-founder",
    "Technology Advisor",
    "Managing Director, Hong Kong",
    "Founder Fellowship - ODF11",
    "CEO and Managing Director",
    "Founder and managing director",
    "Founder & Managing Director",
    "Support Staff",
    "Founder & CEO ",
    "Advisory Board",
    "Practice Manager",
    "Director of IT",
    "SEO and Content Lead",
    "Owner, President, Attorney",
    "Managing Partner | Founder",
    "Chief Revenue Officer, Americas",
    "Founder & Chairman",
    "Propriet√°rio",
    "Director",
    "Non Executive Director",
    "Head Of Digital Marketing",
    "Group Director - People & Culture",
    "Group Marketing Manager",
    "Arbitrator",
    "Partner ",
    "Technology Partner Manager",
    "Commercial And Marketing Director",
    "Professor Legal Innovation",
    "Senior BD and Marketing Manager",
    "Partner and Managing Director",
    "Digital Director",
    "Former Managing Director",
    "CEO, DealMaker",
    "CTO Global",
    "Owner and Managing Partner",
    "President of Shared Services",
    "Chief Business Growth Officer",
    "Associate Alumni",
    "Founder / CEO",
    "President of Discovery Services",
    "Chairman & CEO",
    "Chief Executive Officer- Singapore",
    "Founder and President",
    "Chief Investment Officer",
    "Counsel",
    "Associate Member ",
    "Chief Information Security Officer",
    "Senior Sales Executive",
    "Chief Revenue Officer & Co-Founder",
    "Co-Founder & CEO",
    "President-Elect",
    "Founder and Principal",
    "Founding Board Member",
    "Professor",
    "UK Marketing Manager",
    "Director of Growth",
    "Director of Field Marketing",
    "Founder & Owner",
    "Marketing Technology Coordinator",
    "Managing Director / Shareholder",
    "Chief Commercial Officer (CCO)",
    "Transformation Manager",
    "Chief Risk Officer (CRO)",
    "Patent Agent",
    "People Business Partner",
    "Communication & Marketing Director ",
    "Business Development Manager ",
    "Vice President of Marketing",
    "Founder & Principal",
    "Senior Business Development Coach",
    "Co Managing Partner",
    "Digital Transformation Manager",
    "Director & Owner (Part time)",
    "Managing Director & CEO ",
    "Regional Co-Managing Partner ",
    "Head of Group Knowledge",
    "Group Managing Director",
    "Owner/ Partner",
    "Head of Corporate/M&A, Partner",
    "Executive Director ",
    "Ambassador Finland",
    "CEO and Practice Leader",
    "Managing Partner of Campbelltown",
    "Staff Team Lead",
    "Partner & Executive Director",
    "President, Data Services",
    "Co-Founder - CEO",
    "Non-Executive Director",
    "Partner, Copenhagen",
    "Advisory Board Member",
    "Advisor",
    "Leader",
    "COO/Marketing Director",
    "Marketing Manager, EMEA ",
    "Business Development Manager",
    "Chief Marketing Officer (CMO)",
    "Senior Attorney (Partner)",
    "Co-Founder / COO / CIO",
    "Director de asuntos corporativos",
    "National Marketing & BD Advisor",
    "Head of Digital Optimisation",
    "BD & Marketing Director",
    "Chief Innovation Officer",
    "CEO | Founder",
    "Shareholder",
    "Head of Real Estate Commercial",
    "Owner and Inventor",
    "SOCIO DIRECTOR- Managing Partner",
    "Special Magistrate",
    "President, School Board",
    "Chairman and Director",
    "Area Director",
    "Outsourced Legal Services",
    "Marketing Coordinator",
    "Business Head, APAC and Europe",
    "Marketing Operations Manager",
    "Director of Transformation",
    "Head Of Strategy",
    "Marketing Executive",
    "Head of Client Development & Brand",
    "CEO and General Counsel",
    "Business Development",
    "Chief Client Relations Officer",
    "Front-End Developer",
    "Fractional CEO",
    "Senior Associate",
    "Partner, Co-Founder",
    "Regional Director",
    "Chair of Partners",
    "Member/CEO",
    "Shareholder and Friend",
    "Director, Legal Managed Services",
    "Attorney/Founder & Managing Partner",
    "Founder & Executive Director",
    "Chairperson",
    "Business Owner",
    "Board of Governor",
    "Beachhead Advisor - Egypt",
    "Managing Partner LA office",
    "Adjunct Professor- Oil and Gas",
    "Marketing & Recruiting Director",
    "Managing Partner & CEO",
    "Head Of Operations",
    "Contributor",
    "Partner, Head of Brands Group",
    "Chief Strategy & Marketing Officer",
    "Diretor geral",
    "Vice President (Legal)",
    "President and Managing Director",
    "AWA Group CEO",
    "Pr√©sident",
    "Legal Counsel",
    "Managing Partner/Gesch√§ftsf√ºhrer",
    "Chief Business Officer",
    "General Counsel & SVP US Operations",
    "Managing Partner, San Francisco",
    "Member Of The Supervisory Board",
    "Board Trustee",
    "CEO/Managing Partner",
    "Member of the Board of Directors",
    "Head Of Client Services",
    "Head of IP, Partner",
    "Head of Product",
    "Chief Ethics and Compliance Officer",
    "CEO, Clairvolex Inc.",
    "Investor and Consultant",
    "Firm Managing Partner",
    "Director, Corporate and Commercial",
    "Mediator and Arbitrator",
    "Lawyer Assistance Committee, Member",
    "Strategy & Operations Director",
    "Director Business Transformation",
    "Gerente Nacional de Marketing",
    "Marketing & BD Director",
    "Partner, Co-Head of Corporate M&A",
    "EVP, General Counsel",
    "Partner -- Head of M&A",
    "Senior VP of Strategy",
    "Chief Strategy Officer",
    "Chief Revenue Officer (CRO)",
    "CEO Conveyancing Services ",
    "Director of Practice Development",
    "Head of Corporate ",
    "CEO and co-founder",
    "Vice President",
    "Head - Client Relations",
    "President/CEO",
    "CEO & Founder",
    "Managing Partner - Perth",
    "Founding Steering Committee Member",
    "People Development Business Partner",
    "Managing Partner (Germany)",
    "Chairman Of The Board Of Directors",
    "Co-Founder and Operation Director",
    "Chief Operating Officer, Co-Founder",
    "Senior Vice President",
    "Chair Of The Board Of Directors",
    "General Counsel and Board Member",
    "Head of Acquisition",
    "Marketing Managerin",
    "Managing Director - USA & Canada ",
    "Head of Service Transformation",
    "Vice President, Global Operations",
    "GM Digital and Marketing ",
    "Senior Legal Counsel",
    "Talent Acquisition Team Manager ",
    "Head of IT Development",
    "Advisor To Chief Executive Officer",
    "Chief Operations Officer",
    "VP, Chief Compliance Officer",
    "CEO / Board Director",
    "Partner, Managing Director",
    "Regional Sales Executive",
    "Commercial Arbitrator",
    "Avocat, G√©rant",
    "Managing Director / Board Member",
    "Executive Managing Director",
    "Lawyer (Pro Bono)",
    "In-house Legal Counsel",
    "Managing Principal",
    "VP, General Counsel & Secretary",
    "Partner (M&A)",
    "Managing Partner - Middle East",
    "CEO & President",
    "Senior Counsel",
    "Corporate Counsel ",
    "Solicitor and Managing Director",
    "Associate Attorney",
    "Succession Law Committee Member",
    "Co-Founder & CTO",
    "Gerente de Marketing",
    "Head of Marketing & Communications",
    "Social Media Director, NY Chapter",
    "CEO L√©gicall",
    "Vice President Legal",
    "Manager, People and Culture",
    "Partner, Head - M&A Practice Group",
    "CEO, founder",
    "Head of Communications",
    "Chief Business Development Officer",
    "Owner/Director/Consultant",
    "President - Anaqua Services",
    "AVP - Business",
    "Steering Committee",
    "Head of International ‚Äì Legal ",
    "Chief Executive Partner",
    "Managing Director, Singapore",
    "Corporate Recruiter & HR Officer",
    "Solicitor Director",
    "Angel Investor",
    "Director Human Resources",
    "Presidente",
    "Chairman and Managing Director",
    "Founder | CEO",
    "Founding Partner",
    "Socia directora",
    "Managing Partner, Los Angeles",
    "Councilmember",
    "externer Datenschutzbeauftragter",
    "Managing Director, Serbia",
    "Lecturer",
    "Consejero delegado",
    "Marketing & Communications Manager ",
    "Marketing & Communications Manager",
    "Director Legal - Corporate/M&A",
    "Regional Sales Director",
    "Directrice des ressources humaines",
    "Search Consultant",
    "Manager marketing en communicatie",
    "Head of Sales Demand Generation",
    "Chief Growth Officer",
    "Senior Digital Manager",
    "Owner and Director",
    "Head Of Clients and Markets",
    "Director of Business Services ",
    "Sales Business Development Manager",
    "Associate Partner",
    "GC & Managing Director",
    "Global Managing Partner",
    "Partner : Corporate BU Head",
    "Managing Partner London",
    "Director IT Applications",
    "CEO/Co-Founder",
    "Managing Partner and CEO",
    "Partner, Head of Corporate",
    "Vice Chair, Board of Appeals",
    "Partner, Corporate Finance",
    "Joint Managing Partner",
    "Attorney/Partner",
    "Co-Owner",
    "Partner and Vice Chair, Tech Group",
    "Summit Fellows Mentor",
    "Innovation & Engagement Manager",
    "Co-Founder & CIO",
    "Director, Client Growth & Success  ",
    "Managing Legal Director",
    "Director & General Counsel",
    "Head of Business Development, Asia",
    "CEO / Publisher",
    "Chief Recruiting Officer",
    "COO",
    "Managing Director, New Markets ",
    "Head Of Communication",
    "Vice President, Advanced Analytics",
    "Irvine Office Managing Partner",
    "Compliance Network Lead",
    "Founder, Chief Operating Officer",
    "Consejero Delegado / CEO",
    "Managing Attorney, Midwest Office",
    "President & CEO",
    "Principal Attorney",
    "Barrister",
    "Managing Partner HSR LAW",
    "Associate Product Counsel",
    "Senior Vice President/Partner",
    "Member of the Board of Trustees ",
    "Member, Board Of Trustees",
    "Gesch√§ftsf√ºhrender Gesellschafter",
    "Venture Capital Partner",
    "Director, Associate General Counsel",
    "Marketing and Events Manager",
    "Head of International Development",
    "Marketing and Intake Director",
    "Group Head of Business Development",
    "Head of Client Development ",
    "Head of Platform Division",
    "Chief Experience Officer",
    "Director, Business Development",
    "Client Solutions Director",
    "Senior Pricing Manager",
    "Head of Swiss Office",
    "Freelance Consultant",
    "Partner & Location Head",
    "Principal Owner",
    "Co-Founder Legal Director",
    "Paralegal",
    "Director of Clerking ",
    "Partner/Member",
    "Rechtsanwalt, Partner",
    "Group Commercial Director",
    "Partner and Co-Founder",
    "Advokat and Founder",
    "Vice Chairman Supervisory Board",
    "Chair, Co-Managing Partner",
    "Volunteer",
    "Digital Marketing Director",
    "Vice President Business Operations",
    "Managing Director, UK",
    "Accounting Manager",
    "Mayor",
    "Chief Enterprise Officer (CEnO)",
    "Head Of Internal Audit",
    "Regoinal Managing Partner",
    "VP, Enterprise Markets EMEA",
    "Chief Information Officer",
    "Director - Corporate & Commercial",
    "Owner and Founding Partner",
    "Company Owner",
    "Partner - Head of Corporate",
    "Global Alliance Director",
    "Senior Managing Counsel",
    "Officer Corporate and M&A Committee",
    "Senior Adviser",
    "Global Director ",
    "Limited Partner",
    "Partner - Media and IP",
    "Board Chair",
    "Head Marketing & Communications",
    "Director, Corporate Development",
    "Director of Marketing and Outreach",
    "VP of Marketing",
    "Diretor de Neg√≥cios",
    "Chief Marketing & Customer Officer",
    "Digital Acquisition ",
    "Vice President, Strategic Alliances",
    "CIO & Managing Director",
    "Head of BD & Marketing",
    "Senior Resourcing Business Partner",
    "Client Account Director",
    "Founder & Partner",
    "Director, Brand Counsel",
    "Consultant - Business Development",
    "National CEO",
    "Socio fundador Director",
    "CEO de Data Legal Drive",
    "Industrial Development",
    "Sessional Academic ",
    "Legal Advisor",
    "member of the advisory board",
    "Founder & Director",
    "CEO & Partner",
    "Board Trustee (Non-Executive)",
    "Member of the Executive Board",
    "Chairman/Partner",
    "Group CFO",
    "Adjunct Professor - Trial Advocacy ",
    "D-backs for Change Mentee",
    "Enterprise Solutions ",
    "Entrepreneur-In-Residence",
    "Directora Corporativa y RRHH",
    "Chief Marketing and Revenue Officer",
    "Managing Partner - Avalon",
    "Senior Executive Search Consultant",
    "Marketing Technology Manager",
    "Country Marketing Manager DACH",
    "Marketing Specialist",
    "Director of Marketing & Training",
    "Head of Client Experience",
    "Freelance Journalist",
    "Inhouse lawyer",
    "Marketing Content Manager",
    "Director of Human Resources",
    "Advokat, del√§gare",
    "Head Digital and Innovation",
    "Board Of Directors",
    "Managing Director - UK",
    "Board of Governors Member",
    "Chairman and Managing Partner",
    "Founder and CLO",
    "Office Managing Partner",
    "Fellow, Board of Trustees",
    "Director of Education Partnerships",
    "Chairman/Managing Partner",
    "Principal Lawyer, Head of Insurance",
    "Program Board Member",
    "Investment Manager",
    "Millennium Fellow",
    "Board of Editors Member",
    "Partner, Co-Chair",
    "Advisory Committee Member",
    "Director Marketing",
    "Managing Director, Legal",
    "Strategic Growth Consultant",
    "Managing Partner-Anaheim",
    "CEO/Mindset Coach",
    "Head of Community and Engagement",
    "Director of Intellectual Property",
    "Managing Partner (Budapest)",
    "Director of Customer Success",
    "Director, Markets and Growth",
    "Governor",
    "Acquisitions Marketing Manager",
    "Managing Partner-Houston",
    "Partner/Owner ",
    "Partner/Founder",
    "Sr. Director of Client Solutions",
    "Senior Fellow",
    "Firm Owner",
    "Visiting Lecturer",
    "Independent Director",
    "Rechtsanwalt",
    "Co-founder & Chief Autonomy Officer",
    "Managing Partner of DC Office",
    "Co-Founder/President",
    "Member-Attorney",
    "Director of Diversity and Inclusion",
    "Associate Member",
    "Socio Director de Dictum Andaluc√≠a",
    "Marketing & Communication Director",
    "Real Estate Agent",
    "Director of Product Engagement",
    "Director - Client Solutions",
    "VP of Sales",
    "MD",
    "Director general",
    "VP LegalTech",
    "Member of the Council (Pro Bono)",
    "Propietario",
    "Director of Client Service",
    "First Mover Fellow",
    "Adjunct Associate Professor",
    "Group Privacy Manager",
    "Partner, Knowledge Management Head",
    "Presidenta",
    "Chief Operating Officer, emeritus",
    "Ambassador for Croatia",
    "Empreendedor",
    "Senior Partner",
    "Fundraising Board Member",
    "Chief Executive & Partner",
    "Director, District H",
    "Investor",
    "CEO/CFO",
    "Director Of Marketing & Operations",
    "Cofundadora de AyudaT Pymes.",
    "Director and Co-Founder",
    "Research & Digital Product Director",
    "Head of International",
    "Manager, Business Development",
    "Head of Client Programmes",
    "Managing Director, APAC",
    "Partner, International Arbitration",
    "Partner (Owner)",
    "Firm Administrator",
    "Managing Partner, CEO",
    "Managing Director Singapore",
    "Vice Chairman and Director",
    "Private Consultant ",
    "Of Counsel",
    "Public Information Committee Member",
    "Co-Founder. Socio Director",
    "Managing Partner Peru",
    "International Executive Director",
    "Attorney-At-Law, Partner and owner",
    "Senior Resident Partner",
    "Legal Director - Title and Escrow",
    "Equity Partner, Real Estate Chair",
    "Mediator",
    "Lehrbeauftragter",
    "Manager, Marketing & Engagement",
    "Marketing / Event Manager",
    "Communications and Brand Manager",
    "Group Chief People Officer",
    "Director, Mid-Market, Florida ",
    "Business Transformation Manager",
    "Media Artist",
    "Diretor Jur√≠dico (General Counsel)",
    "Senior Proposal Marketing Manager",
    "Chief Personnel Officer",
    "Founding Executive member",
    "Diretor",
    "Group Head ",
    "Attorney at law and Legal Counsel",
    "Instructor",
    "Managing Principal - Singapore",
    "Founder, CEO",
    "Strategic Advisor",
    "Vice Chairman",
    "Gr√ºnder und Vorstandsvorsitzender",
    "Board Observer",
    "Chief Technology Officer",
    "Director of Corporate Development",
    "Director of Digital",
    "CEO | Attorney-at-law",
    "Senior Vice President, Distribution",
    "Vice President Of Technology",
    "National Marketing Director",
    "Chief Financial Officer",
    "Interim Chief Compliance Officer",
    "Chief M&A Counsel",
    "Director of Business Intelligence",
    "Legal Manager & Board Secretary ",
    "Corporate Committee Member",
    "Director of Strategy and Marketing",
    "Co-Founder, Chief Impact Officer",
    "Manager, TM Adoption & Growth",
    "Managing Partner, Kenya",
    "CEO and Member",
    "Founder-Managing Partner",
    "Advokat/Trusted Advisor/Founder",
    "Owner CEO",
    "Managing Partner - World",
    "Visiting Professor",
    "Co-Chair Anti-Corruption Committee ",
    "Board of Governors, Member",
    "Frontend Web Developer",
    "Global Head of Digital Marketing",
    "Director of Marketing Operations",
    "Senior Manager, Digital Marketing",
    "Practice Group Marketing Manager",
    "Senior Marketing Technology Manager",
    "Head of BGA/Institutional Marketing",
    "Director, Marketing Technology",
    "Director of Business Development ",
    "Senior Regional Marketing Manager",
    "Marketing Technology Specialist",
    "Director of Marketing Services",
    "Senior Manager, Growth Marketing",
    "Marketing & Events Specialist",
    "Assistant Director of Marketing",
    "Sr. Regional Marketing Coordinator",
    "Senior Marketing Specialist",
    "Senior Marketing Data Coordinator",
    "Business Development ",
    "Office Coordinator",
    "Database Marketing Coordinator",
  ];

  return jobList;
}
